server:
    port: 8087

spring:
    datasource:
        url: jdbc:postgresql://localhost:5434/ead-authuser
        username: postgres
        password: 123456
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc: 
                lob.non-contextual-creation: true 
        propeties:
            hibernate:
                show_sql: true